- hosts: demo
  become: true
  tasks:
  - name: Install git, maven 
    package: name={{item}} state=present
    loop:
     - git
     - maven
  - name: Clone the code 
    git: repo=https://github.com/eibay/simple-java-maven-app dest=/tmp/eibay
  - name: Execute maven command to build the code
    command: chdir=/tmp/eibay mvn package
    
