- hosts: demo
  become: true
  tasks:
  # - name: Install Apache
  #  ansible.builtin.yum:
  #    name: maven=3.2.5
  #    state: present
  - name: Install git
    ansible.builtin.yum:
      name: git
      state: present
  - name: Clone the code 
    git: repo=https://github.com/eibay/simple-java-maven-app dest=/tmp/eibay
  - name: Execute maven command to build the code
    command: chdir=/tmp/eibay mvn package
    
